---
- import_playbook: playbooks/00-build-noctis.yml
- import_playbook: playbooks/CVE-2021-41773.yml
- import_playbook: playbooks/CVE-2017-9841.yml
- import_playbook: playbooks/CVE-2019-11510.yml
- import_playbook: playbooks/CVE-2014-6271.yml
- import_playbook: playbooks/CVE-2022-1388.yml
- import_playbook: playbooks/CVE-2022-26134.yml
- import_playbook: playbooks/CVE-2021-26855.yml
- import_playbook: playbooks/CVE-2023-48795.yml
- import_playbook: playbooks/CVE-2021-44228.yml
- import_playbook: playbooks/CVE-2024-6387.yml
- import_playbook: playbooks/CVE-2023-49103.yml
- import_playbook: playbooks/CVE-2024-4577.yml
- import_playbook: playbooks/CVE-2024-21887.yml
- import_playbook: playbooks/CVE-2023-46805.yml
- import_playbook: playbooks/CVE-2022-22965.yml
- import_playbook: playbooks/CVE-2021-43798.yml
- import_playbook: playbooks/CVE-2023-22527.yml
- import_playbook: playbooks/CVE-2021-22205.yml
- import_playbook: playbooks/CVE-2024-21893.yml
- import_playbook: playbooks/CVE-2026-9082.yml
- import_playbook: playbooks/CVE-2023-7028.yml
- import_playbook: playbooks/CVE-2021-21985.yml
- import_playbook: playbooks/CVE-2023-34960.yml
- import_playbook: playbooks/CVE-2024-55591.yml
- import_playbook: playbooks/CVE-2017-1000353.yml
- import_playbook: playbooks/CVE-2024-27198.yml
- import_playbook: playbooks/CVE-2023-34362.yml
- import_playbook: playbooks/CVE-2022-46169.yml
- import_playbook: playbooks/CVE-2023-22518.yml
- import_playbook: playbooks/CVE-2023-46747.yml
