---
- name: Create isolated container network
  ansible.builtin.command:
    cmd: "{{ container_runtime }} network create {{ container_network }}"
  register: net_create
  failed_when: net_create.rc != 0 and 'already exists' not in net_create.stderr
  changed_when: net_create.rc == 0

- name: Run CVE test
  ansible.builtin.include_tasks: run_cve_test.yml
