---
- name: "Build noctis server image"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Build noctis:ci image
      ansible.builtin.command:
        cmd: podman build -t noctis:ci .
        chdir: "{{ playbook_dir }}/../.."
      changed_when: true
