---
- name: "Stop noctis REST servers"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Stop and remove noctis server containers
      ansible.builtin.command:
        cmd: "podman rm -f noctis-plain noctis-oob"
      failed_when: false
      changed_when: true
