#!/usr/bin/env python3
"""Generate infra/docker/MOCKS.md — which vulnerability tests consume which mock.

Run via `task mocks-manifest` (from infra/) after adding or reusing a mock image.
Use --check to verify the committed file is up to date (used by CI).
"""
import glob
import os
import re
import sys

REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
MANIFEST_PATH = os.path.join(REPO_ROOT, "infra", "docker", "MOCKS.md")


def mock_name(docker_image: str) -> str:
    name = docker_image.split("/")[-1].split(":")[0]
    return name


def build_manifest() -> dict[str, list[str]]:
    consumers: dict[str, set[str]] = {}
    pattern = os.path.join(REPO_ROOT, "infra", "inventories", "*", "*", "hosts.yml")
    for hosts_path in sorted(glob.glob(pattern)):
        vendor = os.path.basename(os.path.dirname(os.path.dirname(hosts_path)))
        vuln_id = os.path.basename(os.path.dirname(hosts_path))
        with open(hosts_path) as f:
            content = f.read()
        for image in set(re.findall(r'docker_image:\s*"([^"]+)"', content)):
            name = mock_name(image)
            consumers.setdefault(name, set()).add(f"{vendor}/{vuln_id}")
    return {name: sorted(ids) for name, ids in sorted(consumers.items())}


def render(manifest: dict[str, list[str]]) -> str:
    lines = [
        "<!-- Generated by scripts/gen_mocks_manifest.py — do not edit by hand. -->",
        "<!-- Regenerate with: task mocks-manifest -->",
        "",
        "# Mock image consumers",
        "",
        "Which vulnerability tests (`tests/vulnerabilities/<vendor>/<id>.yaml`) rely on",
        "each `infra/docker/<mock>/` image. A mock listed with more than one consumer is",
        "a **shared mock** — before changing its `server.py`, read every consumer's feed",
        "and re-run `task test ID=<id>` for each of them, not just the one you're adding.",
        "",
    ]
    for name, ids in manifest.items():
        lines.append(f"## {name}")
        for vuln_id in ids:
            lines.append(f"- {vuln_id}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    manifest = build_manifest()
    rendered = render(manifest)

    if "--check" in sys.argv:
        if not os.path.isfile(MANIFEST_PATH):
            print(f"MISSING: {MANIFEST_PATH}", file=sys.stderr)
            return 1
        with open(MANIFEST_PATH) as f:
            current = f.read()
        if current != rendered:
            print(
                f"{MANIFEST_PATH} is stale — run `task mocks-manifest` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("MOCKS.md is up to date.")
        return 0

    with open(MANIFEST_PATH, "w") as f:
        f.write(rendered)
    shared = {n: ids for n, ids in manifest.items() if len(ids) > 1}
    print(f"Wrote {MANIFEST_PATH} ({len(manifest)} mocks, {len(shared)} shared).")
    for name, ids in shared.items():
        print(f"  shared: {name} <- {', '.join(ids)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
