---
container_runtime: podman
container_network: noctis_test_net
docker_dir: "{{ playbook_dir }}/../docker"
noctis_feeds_dir: "{{ playbook_dir }}/../../tests"
noctis_bin: "{{ playbook_dir }}/../../target/debug/noctis"
scan_timeout: 30
